name: SyntrixLobby
main: net.lyzrex.syntrix.lobby.SyntrixLobby
version: ${version}
api-version: "1.21"
softdepend:
  - LythCore
  - MurmelEssentials
author: Lyzrex
website: https://github.com/lyzrex
description: LobbySystem for Lythrion

commands:
  spawn:
    description: Teleports you to the lobby spawn or toggles auto-join teleport.
  setspawn:
    description: Sets the lobby spawn to your current location.
  lobbyreload:
    description: Reloads config/messages and refreshes services.
  build:
    description: Toggles build mode (creative, no lobby item enforcement).
  skull:
    description: Gives you the head of a player.
  setheight:
    description: Sets the death height for the height guard.
  vanish:
    description: Toggles vanish (invisible/visible).
    aliases: [v]
  time:
    description: Controls lobby time (freeze/lock).
  fly:
    description: Toggles player flight in the lobby.
  jumpandrunholo:
    description: Manages the Jump & Run leaderboard hologram.
  stats:
    description: Shows personal lobby statistics.
  verify:
    description: Start the Discord verification process.
    usage: /verify <DiscordName>
  lobbyaction:
    description: Internal command for NPCs.
  viparea:
    description: Sets the corners for the VIP area.
    permission: syntrix.admin